# Generated by Django 5.0 on 2023-12-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_accountmodel_name_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, verbose_name='Токен')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата сгорания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountmodel')),
            ],
        ),
    ]
