# Generated by Django 5.0 on 2023-12-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenmodel',
            options={'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.RenameField(
            model_name='tokenmodel',
            old_name='user',
            new_name='account',
        ),
    ]
