# Generated by Django 4.1.5 on 2023-11-05 14:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_audienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('geography', models.JSONField(default=dict, verbose_name='География показов')),
                ('category', models.JSONField(default=dict, verbose_name='Категории и подкатегории')),
                ('interest', models.JSONField(default=dict, verbose_name='Интересы')),
                ('gender_age', models.JSONField(default=dict, verbose_name='Пол и возраст')),
                ('device', models.JSONField(default=dict, verbose_name='Устройства')),
                ('solvency', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('top1', 'Топ 1%'), ('top2_5', '2-5%'), ('top6_10', '6-10%'), ('top11_40', '11-40%')], max_length=40), default=list, size=None)),
            ],
            options={
                'verbose_name': 'Аудитория компании',
                'verbose_name_plural': 'Аудитории компаний',
            },
        ),
        migrations.CreateModel(
            name='ad_bannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на рекламируемую страницу')),
                ('title_option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=5)),
                ('description_option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=5)),
                ('image_option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=5)),
                ('video_option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=5)),
                ('audio_option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=5)),
                ('channel_private_bool', models.BooleanField(default=True, verbose_name='Показ на закрытых медиаресурсах?')),
                ('ad_audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bannerModel_ad_audienceModel', to='ad_advertiser.ad_audiencemodel')),
            ],
            options={
                'verbose_name': 'Баннер компании',
                'verbose_name_plural': 'Баннеры компаний',
            },
        ),
        migrations.CreateModel(
            name='ad_companyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_finish', models.DateTimeField(verbose_name='Дата завершения')),
                ('budget_week', models.PositiveIntegerField(verbose_name='Недельный бюджет')),
                ('channel_taboo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=500)),
                ('phrase_plus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=500)),
                ('phrase_minus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=500)),
            ],
            options={
                'verbose_name': 'Рекламная компания',
                'verbose_name_plural': 'Рекламные компании',
            },
        ),
        migrations.CreateModel(
            name='profileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('data_legal_country', models.CharField(choices=[('by', 'Беларусь'), ('ru', 'Россия')], max_length=65, verbose_name='Юр.данные. Страна')),
                ('data_legal_currency', models.CharField(choices=[('rub', 'рубль')], max_length=40, verbose_name='Юр.данные. Валюта')),
                ('data_legal_form', models.CharField(choices=[('entity_legal_rf', 'Юридическое лицо (РФ)'), ('person_natural_rf', 'Физическое лицо (РФ)'), ('individual_entrepreneur_rf', 'Индивидуальный предприниматель (РФ)'), ('entity_legal_foreign', 'Иностранное юридическое лицо'), ('person_natural_foreign', 'Иностранное физическое лицо')], max_length=40, verbose_name='Юр.данные. Организационно-правовая форма')),
                ('data_legal_id', models.CharField(choices=[('inn', 'ИНН'), ('inn_vat', 'ИНН/VAT')], max_length=10, verbose_name='Юр.данные. Идентификатор организации')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_advertiser_profileModel', to='account.accountmodel')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='siteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('domain', models.CharField(max_length=255, verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.CreateModel(
            name='targetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('target_action_price', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=2), size=10)),
                ('ad_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetModel_ad_companyModel', to='ad_advertiser.ad_companymodel')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetModel_siteModel', to='ad_advertiser.sitemodel')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='statisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_all', models.PositiveIntegerField(default=0, verbose_name='Всего кликов')),
                ('expense_all', models.PositiveIntegerField(default=0, verbose_name='Расходы (без НДС)')),
                ('expens_vat_all', models.PositiveIntegerField(default=0, verbose_name='Расходы (с НДС)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.profilemodel')),
            ],
            options={
                'verbose_name': 'Статистика профиля',
                'verbose_name_plural': 'Статистика профилей',
            },
        ),
        migrations.CreateModel(
            name='site_ratingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('action', models.CharField(choices=[('plus_no_cons', 'Отсутствие минусов (определенное время у активных компаний)'), ('plus_renewal', 'Продление (рекламной компании)'), ('minus_stop', 'Остановка'), ('minus_reduction_period', 'Сокращение срока'), ('minus_budget_reduction', 'Сокращение бюджета'), ('minus_reduction_target_action_price', 'Снижение цены целевого действия'), ('minus_obscene_content', 'Непристойный контент (степень тяжести от 1 до 3)')], max_length=100, verbose_name='Действие (в зависимости от пункта списка повысится\\понизится рейтинг)')),
                ('action_specify', models.PositiveSmallIntegerField(null=True, verbose_name='Уточнение к действию')),
                ('ad_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_ratingModel_ad_bannerModel', to='ad_advertiser.ad_bannermodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_ratingModel_profileModel', to='ad_advertiser.profilemodel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_ratingModel_siteModel', to='ad_advertiser.sitemodel')),
            ],
            options={
                'verbose_name': 'Рейтинг сайта',
                'verbose_name_plural': 'Рейтинги сайтов',
            },
        ),
        migrations.CreateModel(
            name='site_profileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_profileModel_profileModel', to='ad_advertiser.profilemodel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_profileModel_siteModel', to='ad_advertiser.sitemodel')),
            ],
            options={
                'verbose_name': 'Сайт профиля',
                'verbose_name_plural': 'Сайты профилей',
            },
        ),
        migrations.CreateModel(
            name='setting_notificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_notification_bool', models.BooleanField(default=False, verbose_name='Уведомления для сайта')),
                ('type_notification', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('important', 'Важное'), ('rating_change', 'Изменение рейтинга'), ('ad_company', 'Рекламная кампания'), ('ad_site', 'Подключенный сайт'), ('finance', 'Финансы'), ('access', 'Доступ'), ('technical_support', 'Техподдержка'), ('service_change', 'Изменения в сервисе'), ('referral_program', 'Реферальная программа')], max_length=40), blank=True, default=list, size=None)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_notificationModel_profileModel', to='ad_advertiser.profilemodel')),
                ('social_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_advertiser_setting_notificationModel_social_networkModel', to='account.social_networkmodel')),
            ],
            options={
                'verbose_name': 'Настройка ресурса для получения уведомлений',
                'verbose_name_plural': 'Настройки ресурсов для получения уведомлений',
            },
        ),
        migrations.CreateModel(
            name='notificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_notification_bool', models.BooleanField(default=False, verbose_name='Уведомление для сайта')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('read_bool', models.BooleanField(default=False, verbose_name='Прочитано?')),
                ('type_notification', models.CharField(choices=[('important', 'Важное'), ('rating_change', 'Изменение рейтинга'), ('ad_company', 'Рекламная кампания'), ('ad_site', 'Подключенный сайт'), ('finance', 'Финансы'), ('access', 'Доступ'), ('technical_support', 'Техподдержка'), ('service_change', 'Изменения в сервисе'), ('referral_program', 'Реферальная программа')], max_length=40, verbose_name='Тип уведомления')),
                ('text_notification', models.CharField(max_length=150, verbose_name='Текст уведомления')),
                ('text_button', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('link_button', models.URLField(verbose_name='Ссылка кнопки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationModel_profileModel', to='ad_advertiser.profilemodel')),
                ('social_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_advertiser_notificationModel_social_networkModel', to='account.social_networkmodel')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='finance_operationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('operation', models.CharField(choices=[('put', 'Пополнение'), ('withdraw', 'Вывод')], max_length=20, verbose_name='Тип операции')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('promocode', models.CharField(max_length=20, verbose_name='Промокод')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.profilemodel')),
            ],
            options={
                'verbose_name': 'Финансовая операция',
                'verbose_name_plural': 'Финансовые операции',
            },
        ),
        migrations.CreateModel(
            name='columns_ad_companyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_audience_banner', models.BooleanField(default=True, verbose_name='Аудитории и баннеры?')),
                ('status', models.BooleanField(default=True, verbose_name='Статус?')),
                ('date_start', models.BooleanField(default=True, verbose_name='Дата начала?')),
                ('date_finish', models.BooleanField(default=True, verbose_name='Дата завершения?')),
                ('budget_week', models.BooleanField(default=True, verbose_name='Недельный бюджет?')),
                ('site', models.BooleanField(default=True, verbose_name='Рекламируемый сайт?')),
                ('channel_taboo', models.BooleanField(default=True, verbose_name='Запрещенные медиаресурсы?')),
                ('expense_all', models.BooleanField(default=True, verbose_name='Расход?')),
                ('expens_vat_all', models.BooleanField(default=True, verbose_name='Расход с НДС?')),
                ('cpc', models.BooleanField(default=True, verbose_name='Средняя цена клика?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.profilemodel')),
            ],
            options={
                'verbose_name': 'Компания стобцы таблицы',
                'verbose_name_plural': 'Компании стобцы таблицы',
            },
        ),
        migrations.CreateModel(
            name='columns_ad_bannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_company', models.BooleanField(default=True, verbose_name='Компания?')),
                ('ad_audience', models.BooleanField(default=True, verbose_name='Аудитория?')),
                ('status', models.BooleanField(default=True, verbose_name='Статус?')),
                ('link', models.BooleanField(default=True, verbose_name='Ссылка на рекламируемую страницу?')),
                ('title_option', models.BooleanField(default=True, verbose_name='Варианты заголовков?')),
                ('description_option', models.BooleanField(default=True, verbose_name='Варианты описаний?')),
                ('image_option', models.BooleanField(default=True, verbose_name='Варианты изображений?')),
                ('video_option', models.BooleanField(default=True, verbose_name='Варианты видео?')),
                ('audio_option', models.BooleanField(default=True, verbose_name='Варианты аудио?')),
                ('channel_private_bool', models.BooleanField(default=True, verbose_name='Показ на непроверенных медиаресурсах?')),
                ('phrase_plus', models.BooleanField(default=True, verbose_name='Ключевые фразы?')),
                ('phrase_minus', models.BooleanField(default=True, verbose_name='Минус фразы?')),
                ('expense_all', models.BooleanField(default=True, verbose_name='Расход?')),
                ('expens_vat_all', models.BooleanField(default=True, verbose_name='Расход с НДС?')),
                ('cpc', models.BooleanField(default=True, verbose_name='Средняя цена клика?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.profilemodel')),
            ],
            options={
                'verbose_name': 'Баннер стобцы таблицы',
                'verbose_name_plural': 'Баннеры стобцы таблицы',
            },
        ),
        migrations.CreateModel(
            name='columns_ad_audienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_company', models.BooleanField(default=True, verbose_name='Компания?')),
                ('ad_banner', models.BooleanField(default=True, verbose_name='Баннеры?')),
                ('status', models.BooleanField(default=True, verbose_name='Статус?')),
                ('geography', models.BooleanField(default=True, verbose_name='География?')),
                ('category', models.BooleanField(default=True, verbose_name='Категории?')),
                ('interest', models.BooleanField(default=True, verbose_name='Интересы?')),
                ('gender_age', models.BooleanField(default=True, verbose_name='Пол и возраст?')),
                ('device', models.BooleanField(default=True, verbose_name='Устройства?')),
                ('solvency', models.BooleanField(default=True, verbose_name='Платежеспособность?')),
                ('expense_all', models.BooleanField(default=True, verbose_name='Расход?')),
                ('expens_vat_all', models.BooleanField(default=True, verbose_name='Расход с НДС?')),
                ('cpc', models.BooleanField(default=True, verbose_name='Средняя цена клика?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.profilemodel')),
            ],
            options={
                'verbose_name': 'Аудитория стобцы таблицы',
                'verbose_name_plural': 'Аудитории стобцы таблицы',
            },
        ),
        migrations.AddField(
            model_name='ad_companymodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_companyModel_profileModel', to='ad_advertiser.profilemodel'),
        ),
        migrations.AddField(
            model_name='ad_companymodel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_companyModel_siteModel', to='ad_advertiser.sitemodel'),
        ),
        migrations.AddField(
            model_name='ad_bannermodel',
            name='ad_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bannerModel_ad_companyModel', to='ad_advertiser.ad_companymodel'),
        ),
        migrations.AddField(
            model_name='ad_bannermodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bannerModel_profileModel', to='ad_advertiser.profilemodel'),
        ),
        migrations.AddField(
            model_name='ad_bannermodel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bannerModel_siteModel', to='ad_advertiser.sitemodel'),
        ),
        migrations.AddField(
            model_name='ad_audiencemodel',
            name='ad_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_audienceModel_ad_companyModel', to='ad_advertiser.ad_companymodel'),
        ),
        migrations.AddField(
            model_name='ad_audiencemodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_audienceModel_profileModel', to='ad_advertiser.profilemodel'),
        ),
        migrations.AddField(
            model_name='ad_audiencemodel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_audienceModel_siteModel', to='ad_advertiser.sitemodel'),
        ),
        migrations.CreateModel(
            name='actionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, null=True, verbose_name='ID пользователя неавторизованного')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('action', models.CharField(choices=[('click', 'Клик')], max_length=20, verbose_name='Действие')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена действия')),
                ('geography', models.JSONField(verbose_name='География')),
                ('device', models.CharField(max_length=255, verbose_name='Устройство')),
                ('os', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('browser', models.CharField(max_length=255, verbose_name='Браузер')),
                ('ad_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionModel_ad_bannerModel', to='ad_advertiser.ad_bannermodel')),
                ('ad_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionModel_ad_profileModel', to='ad_advertiser.profilemodel')),
                ('ad_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionModel_siteModel', to='ad_advertiser.sitemodel')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
    ]
