# Generated by Django 4.1.5 on 2023-11-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_network', '0001_initial'),
        ('account', '0001_initial'),
        ('ad_advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='blogger_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionModel_channelModel', to='ad_network.channelmodel'),
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='blogger_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionModel_blogger_profileModel', to='ad_network.profilemodel'),
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actionModel_accountModel', to='account.accountmodel'),
        ),
    ]
