# Generated by Django 5.0 on 2023-12-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_audiencemodel',
            name='category',
            field=models.JSONField(default=list, verbose_name='Категории и подкатегории'),
        ),
        migrations.AlterField(
            model_name='ad_audiencemodel',
            name='device',
            field=models.JSONField(default=list, verbose_name='Устройства'),
        ),
        migrations.AlterField(
            model_name='ad_audiencemodel',
            name='gender_age',
            field=models.JSONField(default=list, verbose_name='Пол и возраст'),
        ),
        migrations.AlterField(
            model_name='ad_audiencemodel',
            name='geography',
            field=models.JSONField(default=list, verbose_name='География показов'),
        ),
        migrations.AlterField(
            model_name='ad_audiencemodel',
            name='interest',
            field=models.JSONField(default=list, verbose_name='Интересы'),
        ),
    ]
