# Generated by Django 5.0 on 2024-01-15 17:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_social_networkmodel_ya_id'),
        ('ad_advertiser', '0003_alter_ad_audiencemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad_companymodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='ad_companymodel',
            name='profile',
        ),
        migrations.AddField(
            model_name='ad_companymodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_companyModel_profileModel', to='account.accountmodel'),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='budget_week',
            field=models.PositiveIntegerField(default=0, verbose_name='Недельный бюджет'),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='channel_taboo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=500),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='date_finish',
            field=models.DateTimeField(blank=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='date_start',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='phrase_minus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, size=500),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='phrase_plus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, size=500),
        ),
        migrations.AlterField(
            model_name='ad_companymodel',
            name='site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_companyModel_siteModel', to='ad_advertiser.sitemodel'),
        ),
        migrations.CreateModel(
            name='ad_statusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Состояние')),
                ('text', models.CharField(max_length=512, verbose_name='Текст')),
                ('companies', models.ManyToManyField(blank=True, related_name='ad_statusModel_companies', to='ad_advertiser.ad_companymodel')),
            ],
        ),
    ]
