# Generated by Django 5.0 on 2024-01-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0004_alter_ad_companymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_companymodel',
            name='status_text',
            field=models.CharField(blank=True, max_length=512, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ad_companymodel',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Показы'),
        ),
    ]
