# Generated by Django 5.0 on 2024-01-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_walletmodel_currency_sign_and_more'),
        ('ad_advertiser', '0005_ad_companymodel_status_text_ad_companymodel_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_audiencemodel',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='ad_bannermodel',
            name='profile',
        ),
        migrations.AddField(
            model_name='ad_audiencemodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_audienceModel_accountModel', to='account.accountmodel'),
        ),
        migrations.AddField(
            model_name='ad_bannermodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_bannerModel_accountModel', to='account.accountmodel'),
        ),
    ]
