# Generated by Django 5.0 on 2024-01-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_walletoperationsmodel_wallet'),
        ('ad_advertiser', '0006_remove_ad_audiencemodel_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_bloggerCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bloggerCompanyModel_account', to='account.accountmodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bloggerCompanyModel_company', to='ad_advertiser.ad_companymodel')),
            ],
        ),
    ]
