# Generated by Django 5.0 on 2024-01-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0007_ad_bloggercompanymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='masked_domain',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Маскированный домен (Переходный)'),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='shows',
            field=models.PositiveIntegerField(default=0, verbose_name='Показы'),
        ),
    ]
