# Generated by Django 5.0 on 2024-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0008_sitemodel_masked_domain_sitemodel_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_bannermodel',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
