# Generated by Django 5.0 on 2024-01-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0010_bannderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_bloggercompanymodel',
            name='account',
        ),
    ]
