# Generated by Django 5.0 on 2024-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0011_remove_ad_bloggercompanymodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_companymodel',
            name='price_target',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена перехода'),
        ),
    ]
