# Generated by Django 5.0 on 2024-02-01 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0013_ad_companymodel_ban_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_bannermodel',
            name='description_option',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=100),
        ),
        migrations.AlterField(
            model_name='ad_bannermodel',
            name='title_option',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=100),
        ),
    ]
