# Generated by Django 5.0 on 2024-02-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0014_alter_ad_bannermodel_description_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_bannermodel',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='ad_bannerModel_images', to='ad_advertiser.bannderimage'),
        ),
    ]
