# Generated by Django 5.0 on 2024-02-03 14:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0015_ad_bannermodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannderimage',
            name='banner',
        ),
        migrations.CreateModel(
            name='statisticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_sum', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('clicks', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, size=102400)),
                ('first_click', models.DateTimeField(blank=True, null=True, verbose_name='Первый клик')),
                ('last_click', models.DateTimeField(blank=True, null=True, verbose_name='Последний клик')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statisticModel_company', to='ad_advertiser.ad_companymodel')),
            ],
        ),
    ]
