# Generated by Django 5.0 on 2024-02-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0016_remove_bannderimage_banner_statisticmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannderimage',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='ad_advertiser.ad_bannermodel'),
        ),
    ]
