# Generated by Django 5.0 on 2024-02-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_jumptoadpage_account'),
        ('ad_advertiser', '0017_bannderimage_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloggerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_bloggerCompanyModel_accountModel', to='account.accountmodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bloggerCompanyModel_company', to='ad_advertiser.profilemodel')),
            ],
        ),
    ]
