# Generated by Django 5.0 on 2024-02-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0018_bloggercompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_bloggerCompanyModel_companyModel', to='ad_advertiser.ad_companymodel'),
        ),
    ]
