# Generated by Django 5.0 on 2024-02-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0020_remove_statisticmodel_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumptoadpage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.sitemodel'),
        ),
    ]
