# Generated by Django 5.0 on 2024-02-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0021_jumptoadpage_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumptoadpage',
            name='company',
        ),
    ]
