# Generated by Django 5.0 on 2024-02-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_advertiser', '0022_remove_jumptoadpage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_companymodel',
            name='budget_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Днейный бюджет'),
        ),
        migrations.AddField(
            model_name='jumptoadpage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.ad_companymodel'),
        ),
    ]
