# Generated by Django 5.0 on 2024-02-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_accountmodel_formorganization_accountmodel_tin'),
        ('ad_advertiser', '0024_ad_companymodel_current_cpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='Сайт')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_rateModel_accountModel', to='account.accountmodel')),
            ],
        ),
    ]
