# Generated by Django 4.1.5 on 2023-11-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('login', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('avatar', models.ImageField(default='index_img/lk/avatar/default.svg', upload_to='account/avatar/', verbose_name='Аватар')),
                ('name_first', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_last', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='verificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('code_verification', models.CharField(max_length=6, verbose_name='Проверочный код')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountmodel')),
            ],
            options={
                'verbose_name': 'Проверочный код',
                'verbose_name_plural': 'Проверочные коды',
            },
        ),
        migrations.CreateModel(
            name='social_networkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('social_network', models.CharField(choices=[('vk', 'ВК'), ('yandex', 'Яндекс'), ('google', 'Google'), ('telegram', 'Telegram'), ('public_services', 'Госуслуги'), ('classmates', 'Одноклассники'), ('my_world', 'Мой мир')], max_length=20, verbose_name='Соцсеть')),
                ('token', models.CharField(max_length=255, verbose_name='Токен')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountmodel')),
            ],
            options={
                'verbose_name': 'Подключенная соцсеть',
                'verbose_name_plural': 'Подключенные соцсети',
            },
        ),
        migrations.CreateModel(
            name='actionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('action', models.CharField(choices=[('log', 'Вход')], max_length=20, verbose_name='Действие')),
                ('geography', models.JSONField(verbose_name='География')),
                ('device', models.CharField(max_length=255, verbose_name='Устройство')),
                ('os', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('browser', models.CharField(max_length=255, verbose_name='Браузер')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountmodel')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия аккаунта',
            },
        ),
    ]
