# Generated by Django 4.2.7 on 2023-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='name_last',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
