# Generated by Django 5.0 on 2023-12-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_name_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='isBlogger',
            field=models.BooleanField(default=False, verbose_name='Блогер'),
        ),
    ]
