# Generated by Django 5.0 on 2024-01-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountmodel_isblogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='phone_number',
            field=models.CharField(default='+7999999999', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
