# Generated by Django 5.0 on 2024-01-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='avatar',
            field=models.ImageField(default='index_img/lk/avatar/default.svg', max_length=1024, upload_to='account/avatar/', verbose_name='Аватар'),
        ),
    ]
