# Generated by Django 5.0 on 2024-01-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_accountmodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='login',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
