# Generated by Django 5.0 on 2024-01-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountmodel_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='avatar',
            field=models.ImageField(default='index_img/lk/avatar/default.svg', max_length=255, upload_to='account/avatar/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='social_networkmodel',
            name='social_network',
            field=models.CharField(choices=[('vk', 'ВК'), ('yandex', 'Яндекс'), ('google', 'Google'), ('telegram', 'Telegram'), ('public_services', 'Госуслуги'), ('classmates', 'Одноклассники'), ('my_world', 'Мой мир')], max_length=32, verbose_name='Соцсеть'),
        ),
    ]
