# Generated by Django 5.0 on 2024-01-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_social_networkmodel_vk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='avatar',
            field=models.CharField(default='index_img/lk/avatar/default.svg', max_length=255, verbose_name='Аватар'),
        ),
    ]
