# Generated by Django 5.0 on 2024-01-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_accountmodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_networkmodel',
            name='ya_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Яндекс ID'),
        ),
    ]
