# Generated by Django 5.0 on 2024-01-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_social_networkmodel_ya_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='walletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('currency_sign', models.CharField(max_length=10, verbose_name='Знак валюты')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.accountmodel')),
            ],
        ),
    ]
