# Generated by Django 5.0 on 2024-01-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_walletmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='currency_sign',
            field=models.CharField(default='₽', max_length=1, verbose_name='Знак валюты'),
        ),
        migrations.CreateModel(
            name='walletOperationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('currency_sign', models.CharField(default='₽', max_length=1, verbose_name='Знак валюты')),
                ('operation', models.CharField(max_length=100, verbose_name='Операция')),
                ('operationType', models.CharField(choices=[('+', 'Пополнение'), ('-', 'Списание')], default='+', max_length=1, verbose_name='Тип операции')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountmodel')),
            ],
        ),
    ]
