# Generated by Django 5.0 on 2024-01-21 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_innvoice_id_walletoperationsmodel_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletoperationsmodel',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.walletmodel'),
        ),
    ]
