# Generated by Django 5.0 on 2024-01-29 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_walletoperationsmodel_wallet'),
        ('ad_advertiser', '0011_remove_ad_bloggercompanymodel_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='jumpToADPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('shows', models.IntegerField(default=0, verbose_name='Показы')),
                ('masked_url', models.CharField(max_length=512, verbose_name='Маскированный URL')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_advertiser.sitemodel')),
            ],
        ),
        migrations.CreateModel(
            name='jumpsToMaskedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('jump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jumptoadpage')),
            ],
        ),
    ]
